import 'package:flutter/material.dart';
import 'package:second_flutter_level/constant_color.dart';

class Plauses {
  String? image;
  String? Title;
  String? SubTitle;
  String? Price;
  Color? firstColor;
  Color? secondColor;
  int? size1;
  int? size2;
  int? size3;
  int? size4;
  Plauses({
    required this.Price,
    required this.SubTitle,
    required this.Title,
    required this.image,
    required this.firstColor,
    required this.secondColor,
    this.size1,
    this.size2,
    this.size3,
    this.size4,
  });
}

List<Plauses> list3 = [
  Plauses(
    Price: "150",
    SubTitle: "this is perfect",
    Title: "Clasic Shoes ",
    image: "images/p1.jpeg",
    firstColor: colormanager.brawn,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "200",
    SubTitle: "this is perfect",
    Title: "Accesories",
    image: "images/p14.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.green,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "150",
    SubTitle: "this is",
    Title: "Dress",
    image: "images/p3.jpeg",
    firstColor: colormanager.black,
    secondColor: colormanager.orange,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "150",
    SubTitle: "this is",
    Title: "Shoes",
    image: "images/p4.jpeg",
    firstColor: colormanager.gray,
    secondColor: colormanager.green,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "150",
    SubTitle: "this is perfect",
    Title: "Watch",
    image: "images/p5.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "200",
    SubTitle: "this is",
    Title: "Watch",
    image: "images/p6.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "700",
    SubTitle: "this is",
    Title: "Plause",
    image: "images/p7.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "150",
    SubTitle: "this is",
    Title: "Shoes",
    image: "images/p8.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "150",
    SubTitle: "this is perfect",
    Title: "Hiles",
    image: "images/p9.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "200",
    SubTitle: "this is",
    Title: "Plause",
    image: "images/p10.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "200",
    SubTitle: "this is",
    Title: "Plause",
    image: "images/p11.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Plauses(
    Price: "200",
    SubTitle: "this is",
    Title: "Plause",
    image: "images/p12.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
];
