import 'package:flutter/material.dart';
import 'package:second_flutter_level/constant_color.dart';
import 'package:second_flutter_level/widgets/detales.dart';

List<Detales> list5 = [
  Detales(
    Price: "150",
    SubTitle: "this is perfect",
    Title: "Clasic Shoes ",
    image: "images/woman1.jpeg",
    firstColor: colormanager.brawn,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "200",
    SubTitle: "this is perfect",
    Title: "Accesories",
    image: "images/woman.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.green,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "150",
    SubTitle: "this is",
    Title: "Dress",
    image: "images/image4.jpeg",
    firstColor: colormanager.black,
    secondColor: colormanager.orange,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "150",
    SubTitle: "this is",
    Title: "Shoes",
    image: "images/men.jpeg",
    firstColor: colormanager.gray,
    secondColor: colormanager.green,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "150",
    SubTitle: "this is perfect",
    Title: "Watch",
    image: "images/watch1.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "200",
    SubTitle: "this is",
    Title: "Watch",
    image: "images/watch2.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "700",
    SubTitle: "this is",
    Title: "Plause",
    image: "images/p1.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "150",
    SubTitle: "this is",
    Title: "Shoes",
    image: "images/shoes4.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "150",
    SubTitle: "this is perfect",
    Title: "Hiles",
    image: "images/p11.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "200",
    SubTitle: "this is",
    Title: "Plause",
    image: "images/h6.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "370",
    SubTitle: "this is",
    Title: "Watch",
    image: "images/h4.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "500",
    SubTitle: "this is",
    Title: "Coesh",
    image: "images/pag2.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "150",
    SubTitle: "this is perfect",
    Title: "Hiles",
    image: "images/shoes1.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
  Detales(
    Price: "200",
    SubTitle: "this is",
    Title: "Coach",
    image: "images/shoes2.jpeg",
    firstColor: colormanager.red,
    secondColor: colormanager.white,
    size1: 28,
    size2: 38,
    size3: 41,
    size4: 35,
  ),
];
